#!/bin/bash
 
volume_step=1
brightness_step=5
max_volume=100
notification_timeout=1000

function get_volume {
    pactl get-sink-volume @DEFAULT_SINK@ | grep -Po '[0-9]{1,3}(?=%)' | head -1
}

function get_brightness {
    brightnessctl -P g
}

function get_volume_icon {
    volume=$(get_volume)
    mute=$(pactl get-sink-mute @DEFAULT_SINK@)
    if [ "$mute" == "Mute: yes" ] ; then
        volume_icon="󰝟 Muted"
    elif [ "$volume" -lt 35 ]; then
        volume_icon="󰕿 Volume"
    elif [ "$volume" -lt 70 ]; then
        volume_icon="󰖀 Volume"
    else
        volume_icon="󰕾 Volume"
    fi
}

function get_brightness_icon {
    brightness_icon="󰖨 Brightness"
}


function show_volume_notif {
    volume=$(get_volume)
    m=""
    if [ "$volume" -gt 100 ]; then
        m=" High volume may cause permanent hearing damage!"
    fi
    get_volume_icon
    notify-send -t $notification_timeout -h string:x-dunst-stack-tag:gosd -h int:value:$volume "$volume_icon" "$m"
}

function show_brightness_notif {
    brightness=$(get_brightness)
    echo $brightness
    get_brightness_icon
    notify-send -t $notification_timeout -h string:x-dunst-stack-tag:gosd -h int:value:$brightness "$brightness_icon"
}

case $1 in
    volume_up)
    pactl set-sink-mute @DEFAULT_SINK@ 0
    volume=$(get_volume)
    if [ $(( "$volume" + "$volume_step" )) -gt 200 ]; then
        pactl set-sink-volume @DEFAULT_SINK@ 200%
    else
        pactl set-sink-volume @DEFAULT_SINK@ +5%
    fi
    show_volume_notif
    ;;

    volume_down)
    pactl set-sink-volume @DEFAULT_SINK@ -5%
    show_volume_notif
    ;;

    volume_mute)
    pactl set-sink-mute @DEFAULT_SINK@ toggle
    show_volume_notif
    ;;

    brightness_up)
    brightnessctl set 5%+
    show_brightness_notif
    ;;

    brightness_down)
    eval "brightnessctl --min-value=47 set 5%- "
    show_brightness_notif
    ;;
esac
